# the connection name
default:
  userName: visitmeta
  userPass: visitmeta
  # try to connect when the data service is started
  useConnectionAsStartup: true
  # url to the ifmap-server for this default connection
  ifmapServerUrl: https://localhost:8443
  subscrptions:
    # the subscription name
    default:
      # identifierType is one of the following:
      # access-request, device, ip-address, mac-address
      # identity as well as extended identifier not supported at the moment
      identifierType: device
      # identifier is the value of the specific identifier
      # when using ip-address as type, the syntax is:
      # IPv4,10.0.0.1
      # or
      # IPv6,...
      identifier: ar:1
      #  send this subscription when the data service is started
      useSubscriptionAsStartup: true